output_dir = '/kaggle/working/data/output'
dataset = '/kaggle/working/examples/dataset.toml'

# training settings
epochs = 15
micro_batch_size_per_gpu = 1
pipeline_stages = 1
gradient_accumulation_steps = 1
gradient_clipping = 1
warmup_steps = 100

# eval settings
eval_every_n_epochs = 1
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1

# misc settings
save_every_n_epochs = 5
checkpoint_every_n_minutes = 60
activation_checkpointing = 'unsloth'
partition_method = 'parameters'
save_dtype = 'bfloat16'
caching_batch_size = 1
steps_per_print = 1
# video_clip_mode = 'single_beginning'
blocks_to_swap = 28

[model]
type = 'wan'
ckpt_path = '/kaggle/working/models/wan2.1'
dtype = 'bfloat16'
transformer_dtype = 'float8'
timestep_sample_method = 'logit_normal'

[adapter]
type = 'lora'
rank = 32
dtype = 'bfloat16'

[optimizer]
type = 'AdamW8bitKahan'
lr = 1e-4
betas = [0.9, 0.99]
weight_decay = 0.01
stabilize = false